name: xcube-cmems
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - xcube >=0.12.1
  - pydap >=3.3.0
  - lxml >=4.9.1
  - owslib
  - pyproj
  - zarr
  - nest-asyncio
  # for testing
  - mock
  - pytest
