name: xcube-cmems
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - xcube >=0.12.1
  - pydap >=3.3.0
  - lxml >=4.9.1
  - owslib
  - pyproj
  - zarr
  - nest-asyncio
  - tenacity
  - aiohttp
  - asyncio
  # pinning the version to overwrite xcube versioning, remove after next xcube
  # release
  - gdal >=3.0,<3.6.3
  # for testing
  - mock
  - pytest

