name: Build

on:
  push:
  release:
    types: [published]
env:
  CMEMS_USERNAME: ${{ secrets.CMEMS_USERNAME }}
  CMEMS_PASSWORD: ${{ secrets.CMEMS_PASSWORD }}

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      NUMBA_DISABLE_JIT: 1
    steps:
      - name: checkout xcube-cmems
        uses: actions/checkout@v3

      - name: Set up MicroMamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      - name: Run unit tests
        shell: bash -l {0}
        run: |  
          pytest --cov=./ --cov-report=xml
          
